elements.goobberry = {
    behavior: behaviors.POWDER,
    breakInto: "juice",
    breakIntoColor: "#5dd507",
    category: "food",
    color: ["#464196", "#5dd507"],
    reactions: {},
    state: "solid",
}

elements.burn_juice = {
    color: "#da1a1a",
    behavior: behaviors.LIQUID,
    reactions: {
        "meat": { "elem2": "cooked_meat" },
        "head": { "elem2": "cooked_meat" },
        "body": { "elem2": "cooked_meat" },
    },
    burn: 100,
    burnTime: 2,
    category: "liquids",
    density: 792,
    stain: -0.25,
    state: "liquid",
    viscosity: 1.15,
}

elements.arsenic = {
    behavior: behaviors.SOLID,
    category: "solids",
    color: "#478800",
    density: 0.5782,
    state: "solid",
    tempHigh: 614, // From what I can gather, arsenic has a melting point hotter than this, but since it turns into gas at this temp, I'll just go with this.
    stateHigh: "arsenic_gas",
    reactions: {
        "blood": { elem1: null, elem2: "arsenic" },
        "water": { elem1: null, elem2: "dirty_water" },
        "salt_water": { elem1: null, elem2: "dirty_water" },
        "sugar_water": { elem1: null, elem2: "dirty_water" },
        "soap": { elem1: null },
        "plant": { elem1: null, elem2: "dead_plant" },
        "evergreen": { elem1: null, elem2: "dead_plant" },
        "cactus": { elem1: null, elem2: "dead_plant" },
        "grass": { elem1: null, elem2: "dead_plant" },
        "vine": { elem1: null, elem2: "dead_plant" },
        "algae": { elem1: null, elem2: null },
        "kelp": { elem1: null, elem2: "dirty_water" },
        "coral": { elem1: null, elem2: "dirty_water", chance: 0.02 },
        "mushroom_spore": { elem1: null, elem2: null },
        "lichen": { elem1: null, elem2: null },
        "yeast": { elem1: null, elem2: null },
        "rat": { elem1: null, elem2: "rotten_meat" },
        "frog": { elem1: null, elem2: "rotten_meat" },
        "tadpole": { elem2: null },
        "fish": { elem1: null, elem2: "rotten_meat" },
        "bird": { elem1: null, elem2: "rotten_meat" },
        "head": { elem1: null, elem2: "rotten_meat" },
        "body": { elem1: null, elem2: "rotten_meat" },
        "homunculus": { elem1: null, elem2: "rotten_meat" },
        "ant": { elem1: null, elem2: "dead_bug" },
        "worm": { elem1: null, elem2: "dead_bug" },
        "fly": { elem1: null, elem2: "dead_bug" },
        "firefly": { elem1: null, elem2: "dead_bug" },
        "bee": { elem1: null, elem2: "dead_bug" },
        "stink_bug": { elem1: null, elem2: "dead_bug" },
        "termite": { elem1: null, elem2: "dead_bug" },
        "spider": { elem1: null, elem2: "dead_bug" },
        "flea": { elem1: null, elem2: "dead_bug" },
        "slug": { elem1: null, elem2: "slime" },
        "snail": { elem1: null, elem2: "limestone" },
        "flower_seed": { elem1: null, elem2: "dead_plant" },
        "pistil": { elem1: null, elem2: "dead_plant" },
        "petal": { elem1: null, elem2: "dead_plant" },
        "grass_seed": { elem1: null, elem2: "dead_plant" },
        "meat": { elem1: null, elem2: "rotten_meat" },
        "cheese": { elem1: null, elem2: "rotten_cheese" },
        "cheese_powder": { elem1: null, elem2: "rotten_cheese" },
        "mushroom_cap": { elem1: null, elem2: null, chance: 0.01 },
        "mushroom_gill": { elem1: null, elem2: null, chance: 0.01 },
        "mushroom_stalk": { elem1: null, elem2: null, chance: 0.01 },
        "pollen": { elem2: null, chance: 0.01 },
        "mushroom_spore": { elem1: null, elem2: null, chance: 0.1 },
        "head": { elem1: null, elem2: "rotten_meat" },
        "body": { elem1: null, elem2: "rotten_meat" },
        "hair": { elem1: null, elem2: null, chance: 0.01 }
    },
}

elements.arsenic_gas = {
    behavior: behaviors.GAS,
    category: "gases",
    color: "#478800",
    density: 0.5782,
    state: "gas",
    temp: 700,
    tempLow: 613,
    stateLow: "arsenic",
    reactions: {
        "blood": { elem1: null, elem2: "arsenic" },
        "water": { elem1: null, elem2: "dirty_water" },
        "salt_water": { elem1: null, elem2: "dirty_water" },
        "sugar_water": { elem1: null, elem2: "dirty_water" },
        "plant": { elem1: null, elem2: "dead_plant" },
        "evergreen": { elem1: null, elem2: "dead_plant" },
        "cactus": { elem1: null, elem2: "dead_plant" },
        "grass": { elem1: null, elem2: "dead_plant" },
        "vine": { elem1: null, elem2: "dead_plant" },
        "algae": { elem1: null, elem2: null },
        "kelp": { elem1: null, elem2: "dirty_water" },
        "coral": { elem1: null, elem2: "dirty_water" },
        "mushroom_spore": { elem1: null, elem2: null },
        "lichen": { elem1: null, elem2: null },
        "yeast": { elem1: null, elem2: null },
        "rat": { elem1: null, elem2: "rotten_meat" },
        "frog": { elem1: null, elem2: "rotten_meat" },
        "tadpole": { elem2: null },
        "fish": { elem1: null, elem2: "rotten_meat" },
        "bird": { elem1: null, elem2: "rotten_meat" },
        "head": { elem1: null, elem2: "rotten_meat" },
        "body": { elem1: null, elem2: "rotten_meat" },
        "homunculus": { elem1: null, elem2: "rotten_meat" },
        "ant": { elem1: null, elem2: "dead_bug" },
        "worm": { elem1: null, elem2: "dead_bug" },
        "fly": { elem1: null, elem2: "dead_bug" },
        "firefly": { elem1: null, elem2: "dead_bug" },
        "bee": { elem1: null, elem2: "dead_bug" },
        "stink_bug": { elem1: null, elem2: "dead_bug" },
        "termite": { elem1: null, elem2: "dead_bug" },
        "spider": { elem1: null, elem2: "dead_bug" },
        "flea": { elem1: null, elem2: "dead_bug" },
        "slug": { elem1: null, elem2: "slime" },
        "snail": { elem1: null, elem2: "limestone" },
        "flower_seed": { elem1: null, elem2: "dead_plant" },
        "pistil": { elem1: null, elem2: "dead_plant" },
        "petal": { elem1: null, elem2: "dead_plant" },
        "grass_seed": { elem1: null, elem2: "dead_plant" },
        "meat": { elem1: null, elem2: "rotten_meat" },
        "cheese": { elem1: null, elem2: "rotten_cheese" },
        "cheese_powder": { elem1: null, elem2: "rotten_cheese" },
        "mushroom_cap": { elem1: null, elem2: null, chance: 0.01 },
        "mushroom_gill": { elem1: null, elem2: null, chance: 0.01 },
        "mushroom_stalk": { elem1: null, elem2: null, chance: 0.01 },
        "pollen": { elem2: null, chance: 0.01 },
        "mushroom_spore": { elem1: null, elem2: null, chance: 0.1 },
        "head": { elem1: null, elem2: "rotten_meat" },
        "body": { elem1: null, elem2: "rotten_meat" },
        "hair": { elem1: null, elem2: null, chance: 0.01 }
    },
}