elements.rebirthite = {
    color: ["#530000", "#FF0000"],
    behavior: behaviors.LIQUID,
    category: "liquids",
    breakInto: ["hydrogen", "water"],
    reactions: {
        "bird": { "elem1": null, "elem2": "sapling" },
        "blood": { "elem1": null, "elem2": "sapling" },
        "body": { "elem1": null, "elem2": "sapling" },
        "bone": { "elem1": null, "elem2": "sapling" },
        "coral": { "elem1": null, "elem2": "sapling" },
        "evergreen": { "elem1": null, "elem2": "sapling" },
        "firefly": { "elem1": null, "elem2": "sapling" },
        "fly": { "elem1": null, "elem2": "sapling" },
        "frog": { "elem1": null, "elem2": "sapling" },
        "grass": { "elem1": null, "elem2": "sapling" },
        "head": { "elem1": null, "elem2": "sapling" },
        "lichen": { "elem1": null, "elem2": "sapling" },
        "meat": { "elem1": null, "elem2": "sapling" },
        "petal": { "elem1": null, "elem2": "sapling" },
        "pistil": { "elem1": null, "elem2": "sapling" },
        "plant": { "elem1": null, "elem2": "sapling" },
        "rat": { "elem1": null, "elem2": "sapling" },
        "root": { "elem1": null, "elem2": "sapling" },
        "snail": { "elem1": null, "elem2": "sapling" },
        "tree_branch": { "elem1": null, "elem2": "sapling" },
        "wood": { "elem1": null, "elem2": "sapling" },
        "worm": { "elem1": null, "elem2": "sapling" },
    },
    state: "liquid",
    density: 1.2,
    viscosity: 2
};

elements.bless.reactions.rebirthite = { elem2: null }
